"""secutty table

Revision ID: 0dd7030adc0b
Revises: 09ead06e5661
Create Date: 2020-01-12 18:19:02.508804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd7030adc0b'
down_revision = '09ead06e5661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_type', sa.String(length=50), nullable=True),
    sa.Column('security_name', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('buy_price', sa.Integer(), nullable=True),
    sa.Column('buy_time', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(length=50), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_buy_time'), 'security', ['buy_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_buy_time'), table_name='security')
    op.drop_table('security')
    # ### end Alembic commands ###
